import React, { useContext } from "react";
import Head from "next/head";
import { FaPlus, FaMinus, FaTimes } from "react-icons/fa";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { CartContext } from "@/context/CartContext";
import { CartContextModal } from "@/context/CartContextModal";

const Layout: React.FC = ({ children }) => {
  const { cart } = useContext(CartContext);
  const { isShowModalCart, setIsShowModalCart } = useContext(CartContextModal);

  return (
    <>
      <Head>
        <title>Landing Manage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <div
        className={`w-screen h-screen bg-[rgba(0,0,0,0.5)] fixed top-0 left-0 z-[3000] ${
          isShowModalCart ? "block" : "hidden"
        }`}
        onClick={() => setIsShowModalCart(false)}
      ></div>
      <div
        className={`fixed w-full md:w-80 h-screen bg-white shadow-xl z-[3100] ${
          isShowModalCart ? "block" : "hidden"
        }`}
      >
        <div className="flex items-center justify-between py-6 px-6">
          <span className="block text-xl font-semibold text-VeryDarkBlue">
            Cart shopping
          </span>
          <div className="-mr-1">
            <button
              className="text-red-500 p-1 text-xl"
              onClick={() => setIsShowModalCart(false)}
            >
              <FaTimes />
            </button>
          </div>
        </div>

        <div className="flex flex-col justify-between px-6 h-[calc(100vh_-_76px)]">
          <div>
            {cart.map((product: any) => (
              <article key={product.id} className="flex items-center mb-4">
                <div className="border border-slate-300 w-20 h-20 p-1">
                  <img
                    src={product.image}
                    className="w-full object-contain"
                    alt=""
                  />
                </div>
                <div className="ml-3 flex-1 flex justify-between">
                  <div>
                    <span className="block text-sm text-slate-600">
                      {product.name}
                    </span>
                    <span className="block font-semibold text-sm mt-1">
                      ${product.price}
                    </span>
                  </div>
                  <div className="ml-6 md:ml-3">
                    <button className="flex items-center justify-center text-xs w-6 h-6 rounded bg-BrightRed text-white">
                      <FaPlus />
                    </button>
                    <span className="text-sm block my-1 text-center font-semibold text-slate-600">
                      2
                    </span>
                    <button className="flex items-center justify-center text-xs w-6 h-6 rounded bg-BrightRed text-white">
                      <FaMinus />
                    </button>
                  </div>
                </div>
              </article>
            ))}
          </div>

          <div className="pb-8">
            <button className="bg-DarkBlue block w-full text-white py-3 rounded-md">
              Realizar compra
            </button>
          </div>
        </div>
      </div>

      <Navbar />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
